### PR TITLE
Daly BMS and USB permissions documentation

### PR DESCRIPTION
**Pull request by klvbdmh**
As discussed in #9 , I added two pages to the documentation:

- Daly BMS setup guide, with example config
- USB permissions guide

Not sure if I put it in the right place in the index - feel free to move it around. I'm also not sure if the writing and the structure has the right style. It's a rough draft which we can further edit.

### CODE REVIEW

**Comment by klvbdmh** [comment]
Some portions of the Daly BMS setup for sure will be duplicated elsewhere, for example the MQTT config section. We could move them elsewhere and use the `.. include::` directive.

**Comment by jblance** [comment]
just merging as its easier to read the result than the source :-)

**Comment by jblance** [comment]
Thanks for this it look great

- Couple of thoughts:
- This looks more like a 'tutorial' to me, so i think we should have a Tutorials section (instead of Devices) and perhaps rename the files 
- perhaps add some comments to the code blocks, describing what and why for the important parts

**Comment by klvbdmh** [comment]
> This looks more like a 'tutorial' to me, so i think we should have a Tutorials section (instead of Devices) and perhaps rename the files

Sure, sounds good. Would you like to keep a Device section for something else?

> perhaps add some comments to the code blocks, describing what and why for the important parts

Yes, makes sense. I'll add inline comments like in the Config File Syntax section.

**Comment by jblance** [comment]
> Would you like to keep a Device section for something else?

Possibly - thought not sure for what at this stage

**Pull request merged**
